name: Dave Wesley
favicon: null
layout_spectrum: 0.01316848723217845
typography_spectrum: 0.8544469161424786
title: Dave Wesley GRID test...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#969492'
    - '#7b7b7b'
    - '#e5e5e5'
    - '#121614'
    - '#c1bfbd'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
